---
# Anarres :: shell
#
# Role to setup shell and CLI packages.
#
- name: Install shell and CLI packages
  community.general.pacman:
    name: "{{ item }}"
    state: latest
  loop:
    - adobe-source-code-pro-fonts
    - htop
    - neovim
    - rbw
    - ripgrep
    - tmux
    - tree
    - zsh
  become: true
  when: ansible_os_family == "Archlinux"

- name: Install AUR CLI packages with yay
  ansible.builtin.command:
    cmd: "yay --noconfirm --noprogressbar --needed --aur --sync {{ item }}"
  loop:
    - oh-my-zsh-git
  register: result
  changed_when: "'there is nothing to do' not in result.stdout"
  when: ansible_os_family == "Archlinux"

- name: Configure shell and CLI apps
  ansible.builtin.include_tasks:
    file: "{{ item }}"
  loop:
    - ohmyzsh.yaml
    - spacevim.yaml

## rbw

- name: Check if rbw Bitwarden client is already configured
  ansible.builtin.command:
    cmd: "rbw config show"
  register: rbw_configured
  changed_when:
    - "rbw_configured.rc != 0"
    - "'failed to load config' in rbw_configured.stderr"
  # only fail if rbw command is missing
  failed_when: "rbw_configured.rc == 127"
  notify: Configure rbw Bitwarden client

## tmux

- name: Configure tmux
  ansible.builtin.template:
    src: "tmux.conf.j2"
    dest: "{{ home }}/.tmux.conf"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0640"
