---
# Anarres :: shell :: ohmyzsh
#
# Role to configure oh-my-zsh.
#
- name: Assure user owns .oh-my-zsh directories
  ansible.builtin.file:
    group: "{{ username }}"
    owner: "{{ username }}"
    path: "{{ home }}/.oh-my-zsh"
    recurse: true
  become: true

- name: Update oh-my-zsh settings in .zshrc
  ansible.builtin.lineinfile:
    line: "{{ item.line }}"
    path: "{{ home }}/.zshrc"
    regexp: "{{ item.regexp }}"
    state: present
  loop:
    - line: "ZSH_THEME={{ zsh.theme }}"
      regexp: "^ZSH_THEME="
    - line: "plugins=({{ zsh.plugins | join(' ') }})"
      regexp: "^plugins="

# make sure pyenv is loaded before plugins, otherwise get warning
- name: Assure pyenv is loaded before plugins in .zshrc
  ansible.builtin.blockinfile:
    append_newline: true
    block: |
      export PYENV_ROOT="$HOME/.pyenv"
      if [[ -e "$PYENV_ROOT" ]]; then
        if [[ "$PATH" != *"$PYENV_ROOT/bin"* ]]; then
          export PATH="$PYENV_ROOT/bin:$PATH"
        fi
        eval "$(pyenv init --path)"
      fi
    # insert block at beginning of file
    insertbefore: "BOF"
    path: "{{ home }}/.zshrc"
    prepend_newline: true

- name: Update custom zsh files
  ansible.builtin.template:
    src: "{{ item }}.j2"
    # note: oh-my-zsh automatically sources all files in $ZSH_CUSTOM i.e. ~/.oh-my-zsh/custom/
    dest: "{{ home }}/.oh-my-zsh/custom/{{ item }}"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0750"
  loop:
    - aliases.zsh
    - custom.zsh
