---
# Anarres :: shell :: spacevim
#
# Role to  configure SpaceVim.
#
- name: Download SpaceVim
  ansible.builtin.get_url:
    url: https://spacevim.org/install.sh
    dest: "{{ home }}/.oh-my-zsh/spacevim-install.sh"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0750"
  notify: Install SpaceVim

- name: Configure SpaceVim
  ansible.builtin.template:
    dest: "{{ home }}/.SpaceVim.d/init.toml"
    group: "{{ username }}"
    mode: "0640"
    owner: "{{ username }}"
    src: "spacevim/init.toml.j2"
