---
# Anarres :: shell :: handlers
#
# Handlers for setting up shell and CLI apps.

- name: Configure rbw Bitwarden client
  ansible.builtin.command:
    cmd: "rbw config set {{ item.key }} {{ item.value }}"
  loop: "{{ rbw | dict2items }}"
  register: rbwconfig
  changed_when: "rbwconfig.rc == 0"
  when:
    # only run when rbw is not configured and email is set
    - "rbw.email is not none"

- name: Install SpaceVim
  ansible.builtin.command:
    cmd: "bash {{ home }}/.oh-my-zsh/spacevim-install.sh"
  register: spacevim_install
  changed_when: "spacevim_install.rc == 0"
