---
# Anarres :: pre
#
# Role to setup pre-requisites prior to running other roles.
#
- name: "Install pre-requisite packages"
  community.general.pacman:
    name: "{{ item }}"
    state: latest
  loop:
    - git
    - yay
  become: true
  when: ansible_os_family == "Archlinux"

## ssh
- name: "Assure user owns their ssh directory"
  ansible.builtin.file:
    group: "{{ username }}"
    mode: "0700"
    owner: "{{ username }}"
    path: "{{ home }}/.ssh/keys"
    recurse: true
    state: directory
  become: true

- name: "Add github to ssh config"
  # note: community.general.ssh_config is _not_ used, as that requires paramiko
  ansible.builtin.blockinfile:
    append_newline: true
    block: |
      Host github.com
        User git
        IdentityFile ~/.ssh/github
        IdentitiesOnly yes
    group: "{{ username }}"
    mode: "0700"
    owner: "{{ username }}"
    path: "{{ home }}/.ssh/config"
    prepend_newline: true

## git
- name: "Add settings to ~/.gitconfig"
  community.general.git_config:
    file: "{{ home }}/.gitconfig"
    name: "{{ item.key }}"
    scope: file
    value: "{{ item.value }}"
  loop: "{{ git | dict2items }}"
