#!/usr/bin/env bash
 
# make sure to source functions.sh first, if exists
if [ -f "~/.zsh/functions.sh" ]; then
    source "~/.zsh/functions.sh"
fi

alias a="alias"
alias b="bundle"
alias be="bundle exec"
alias bek="bundle exec kitchen"
alias bekc="bundle exec kitchen converge -c -l info"
alias bekd="bundle exec kitchen destroy"
alias bekl="bundle exec kitchen list"
alias bekv="bundle exec kitchen verify -c -l info"
alias c="cat"
alias df="df -h"
alias egrep="egrep --color"
alias fixmouse="synclient TouchpadOff=0"
alias ga="git add"
alias gb="git branch"
alias gcam="git commit -S --amend -m"
alias gcm="git commit -S -m"
alias gco="git checkout"
alias gd="git difftool"
alias g="egrep --color"
alias gl="git log --show-signature"
alias gm="git mergetool"
alias gpl="git pull"
alias gplo="git pull origin"
alias gplom="git pull origin master"
alias gplu="git pull upstream"
alias gplum="git pull upstream master"
alias gpo="git push origin"
alias grep="grep --color -E"
alias gr="git remote -v"
alias gst="git status"
alias gt="git tag"
alias h="history"
alias k="bundle exec knife"
alias l="less -r"
alias lrh="lein trampoline repl :headless"
alias ls="ls -x --color -h"
alias mdl="pandoc -s -f markdown -t man | man -l -"
alias mj="make -e -S -j5"
alias m="make -e -S"
alias p="pass"
alias pbcopy="xsel --clipboard --input"
alias pbpaste="xsel --clipboard --output"
alias pc="pygmentize -g"
alias pong="ping www.google.com -c 1 -W 30"
alias pslag="ps -lA | head -n 1; ps -lA | grep -i"
alias pwr="echo \"$(upower -i $(upower -e | grep BAT) | grep percent | sed -e 's/.*: *//') ($(upower -i $(upower -e | grep BAT) | grep state | sed -e 's/.*: *//'))\""
alias rmcolors="sed -r \"s/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[m|K]//g\""
alias rmorig="find -type f | grep -v .git/ | grep orig | xargs rm"
alias rspec="bundle exec rspec --color --format documentation"
alias sshkrm="ssh-keygen -f \"/home/cstedman/.ssh/known_hosts\" -R"
alias t="tree -C"
alias vbox="virtualbox >/dev/null 2>&1"
alias vd="vagrant destroy"
alias vp="vagrant provision"
alias vssh="vagrant ssh"
alias vst="vagrant status"
alias vup="vagrant up"
alias v="vim"
alias xrd="xr DP1"
alias xrh="xr HDMI1"

