---
# Anarres :: web
#
# Install and configure web and GUI apps.
#
- name: Install web and GUI app packages
  community.general.pacman:
    name: "{{ item }}"
    state: latest
  loop:
    - expressvpn
    - feh
    - firefox
    - qbittorrent
  when: ansible_os_family == "Archlinux"
  become: true

# only include when gaming tag is specified
- name: Include tasks for gaming
  ansible.builtin.include_tasks:
    file: gaming.yaml
  tags:
    - never
    - gaming

# only include when streaming tag is specified
- name: Include tasks for streaming
  ansible.builtin.include_tasks:
    file: streaming.yaml
  tags:
    - never
    - streaming
