---
# Anarres :: web
#
# Install and configure web and GUI apps.
#
- name: Install web and GUI app packages
  community.general.pacman:
    name:
      - feh
      - firefox
      - qbittorrent
    state: latest
  when: ansible_os_family == "Archlinux"
  become: true

- name: Install AUR web and GUI packages with yay
  ansible.builtin.command:
    cmd: >
      yay --noconfirm --noprogressbar --needed --aur --sync
      expressvpn
  register: result
  changed_when: "'there is nothing to do' not in result.stdout"
  when: ansible_os_family == "Archlinux"

# only include when gaming tag is specified
- name: Include tasks for gaming
  ansible.builtin.include_tasks:
    file: gaming.yaml
  tags:
    - never
    - gaming

# only include when streaming tag is specified
- name: Include tasks for streaming
  ansible.builtin.include_tasks:
    file: streaming.yaml
  tags:
    - never
    - streaming
