---
# Anarres :: web
#
# Install and configure web and GUI apps.
#
- name: Install web and GUI app packages
  community.general.pacman:
    name: "{{ item }}"
    state: latest
  loop:
    - feh
    - firefox
    - qbittorrent
  when: ansible_os_family == "Archlinux"
  become: true
