---
- name: install web packages
  pacman: name={{ item }} state=latest
  with_items:
  - firefox
  when: ansible_os_family == "Archlinux"

## firefox

# TODO: still care about these?
- name: setup xdg directories config used by firefox
  copy: src="dotconfig/user-dirs.dirs"
        dest="{{ home }}/.config/user-dirs.dirs"
        owner={{ username }} group={{ username }}

