---
- name: install gui packages
  pacman: name={{ item }} state=latest
  with_items:
  - adobe-source-code-pro-fonts
  - feh
  when: ansible_os_family == "Archlinux"

## urxvt

# TODO: necessary or relevant?
- name: configure urxvt
  template: src=dotXresources.j2 dest={{ home }}/.Xresources
            owner={{ username }} group={{ username }} mode=0640

