---
- name: install pre-requisite packages
  pacman: name={{ item }} state=latest
  with_items:
  - git
  - gnupg
  when: ansible_os_family == "Archlinux"

## ssh

- name: assure {{ username }} owns their ssh directory
  file: path={{ ssh.keydir }} state=directory recurse=true
        owner={{ username }} group={{ username }} mode=0700

- name: configure ssh
  template: src=dotssh/config.j2 dest={{ home }}/.ssh/config
            owner={{ username }} group={{ username }} mode=0600

## git

- name: configure git
  template: src=dotgitconfig.j2 dest={{ home }}/.gitconfig
            owner={{ username }} group={{ username }} mode=0600

## gpg/gnupg

- name: assure {{ username }} owns their gnupg directory
  file: path={{ home }}/.gnupg state=directory recurse=true
        owner={{ username }} group={{ username }} mode=0700

- name: use gpg agent
  copy: content=use-agent
        dest={{ home }}/.gnupg/gpg.conf
        owner={{ username }} group={{ username }} mode=0640

- name: configure gpg agent
  template: src=dotgnupg/gpg-agent.conf dest={{ home }}/.gnupg/gpg-agent.conf
            owner={{ username }} group={{ username }} mode=0640
  notify:
  - reload gpgagent
