---
# Anarres :: dev :: docker
#
# Setup docker-based development environment.
#
# This task file is included in main whenever the "docker" tag is not in "--skip-tags".

- name: Install docker dev env packages
  community.general.pacman:
    name:
      - act
      - docker
      - docker-buildx
      - docker-compose
    state: latest
  when: ansible_os_family == "Archlinux"
  become: true

- name: Enable and start docker service
  ansible.builtin.systemd_service:
    name: docker
    enabled: true
    state: started
  become: true

- name: Assure user is in docker group
  ansible.builtin.user:
    name: "{{ username }}"
    append: true
    groups:
      - docker
  become: true
