---
# Anarres :: dev :: python
#
# Setup python-based development environment.
#
# This task file is included in main whenever the "python" tag is not in "--skip-tags".

- name: Install python dev env packages
  community.general.pacman:
    name: "{{ item }}"
    state: latest
  loop:
    - pyenv
  when: ansible_os_family == "Archlinux"
  become: true

- name: Install python dev env packages with pipx
  community.general.pipx:
    name: "{{ item }}"
  loop:
    - black
    - ipython
    - poetry

- name: Assure user owns pyenv dir
  ansible.builtin.file:
    group: "{{ username }}"
    owner: "{{ username }}"
    # note: assumes PYENV_ROOT is $HOME/.pyenv
    path: "{{ home }}/.pyenv"
    recurse: true
    state: directory

- name: Determine python versions installed via pyenv
  ansible.builtin.command:
    cmd: "pyenv versions --bare"
  register: pyenv_versions
  changed_when: "pyenv_versions.stdout_lines | intersect(pyenv.versions | d([]))"
  notify: Install python versions with pyenv
