---
# Anarres :: dev :: python
# 
# Setup python-based development environment.
#
# This task file is included in main whenever the "python" tag is not in "--skip-tags".

- name: Install python dev env packages
  community.general.pacman:
    name: "{{ item }}"
    state: latest
  loop:
    - pyenv
  when: ansible_os_family == "Archlinux"
  become: true

- name: Install python dev env packages with pipx
  community.general.pipx:
    name: "{{ item }}"
  loop:
    - black
    - ipython
    - poetry

- name: Assure user owns pyenv dir
  file:
    group: "{{ username }}"
    owner: "{{ username }}"
    # note: assumes PYENV_ROOT is $HOME/.pyenv
    path: "{{ home }}/.pyenv"
    recurse: true
    state: directory

- name: Determine python versions installed via pyenv
  shell:
    cmd: "pyenv versions --bare"
  register: pyenv_versions

- name: Install python versions with pyenv
  shell:
    cmd: "pyenv install {{ item }}"
  loop: "{{ pyenv.versions }}"
  when: "item not in pyenv_versions.stdout_lines"
