---
# Anarres :: dev :: python
# 
# Setup python-based development environment.
#
# This task file is included in main whenever the "python" tag is not in "--skip-tags".

- name: Install python dev env packages
  community.general.pacman:
    name: "{{ item }}"
    state: latest
  loop:
    - pyenv
  when: ansible_os_family == "Archlinux"
  become: true

- name: Install AUR python dev env packages with yay
  command:
    cmd: "yay --noconfirm --noprogressbar --needed --aur --sync {{ item }}"
  loop:
    - pyenv-virtualenv
  register: result
  changed_when: "'there is nothing to do' not in result.stdout"
  when: ansible_os_family == "Archlinux"

# - name: make sure {{ username }} owns pyenv dir
#   file: path={{ pyenv.dir }} state=directory recurse=true
#         owner={{ username }} group={{ username }}
# 
# - name: get list of installed pythons
#   shell: ls "{{ pyenv.dir }}/versions" 2>&1 || echo ""
#   register: pythons_installed
# 
# - name: install pythons
#   shell: "{{ pyenv.dir }}/bin/pyenv install {{ item }}"
#   become: yes
#   become_user: "{{ username }}"
#   with_items: "{{ pyenv.pythons }}"
#   when: item not in pythons_installed.stdout_lines
