---
name: docs tests
on:
  pull_request:
    paths:
      - .github/workflows/pr-docstests.yaml
      - .markdownlint.yaml
      - '**.md'

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
      # install markdownlint-cli
      - name: Install markdownlint-cli
        run: npm install -g --update-notifier=false markdownlint-cli@0.39.0
      # markdownlint
      - name: Run markdownlint
        run: markdownlint .
